set(L2_ADDR "::0A" CACHE STRING "")
set(L2_MAX_MTU 124 CACHE STRING "")
set(L2_TX_DELAY 500 CACHE STRING "")

set(TUN_NAME "schc_tun0" CACHE STRING "")

set(IPv6_PREFIX "2001:db8" CACHE STRING "")
set(IPv6_PREFIX_LEN "64" CACHE STRING "")
set(IPv6_IID "::10" CACHE STRING "")
set(IPv6_PEER_PREFIX "2001:db8" CACHE STRING "")
set(IPv6_PEER_PREFIX_LEN "64" CACHE STRING "")
set(IPv6_PEER_IID "::11" CACHE STRING "")
set(IPv6_MAX_PACKET_SIZE 256 CACHE STRING "")

option(DROP_NON_COAP "" ON)
if (OSCORE_PROXY_ENABLED)
    option(OSCORE_DROP_ON_ERROR "" ON) # If OFF, sends plain CoAP
    option(REGULAR_COMP "" ON)
    set(OSCORE_INNER_MAX_SIZE 128 CACHE STRING "")
    set(OSCORE_OUTER_MAX_SIZE 192 CACHE STRING "")
    set(NVM_FILENAME "schc_nvm.conf" CACHE STRING "Filename for Non-Volatile Memory storage")
endif ()
